# Generated by Django 4.0.1 on 2022-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TWI', 'TWIN'), ('SIN', 'SINGLE'), ('DOB', 'DOUBLE'), ('SIN-EN', 'SINGLE-ENSUITE'), ('DOB', 'DOUBLE-ENSUITE'), ('HOU', 'WHOLE-HOUSE')], max_length=6, null=True),
        ),
    ]
