# Generated by Django 4.0.1 on 2022-01-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='author',
        ),
    ]
