# Generated by Django 4.0.1 on 2022-01-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_user_booking_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TWI', 'TWIN'), ('SIN', 'SINGLE'), ('DOB', 'DOUBLE'), ('SIN-EN', 'SINGLE-ENSUITE'), ('DOB-EN', 'DOUBLE-ENSUITE'), ('HOU', 'WHOLE-HOUSE')], max_length=6, null=True),
        ),
    ]
